/**
 * Update Disposable Domains List
 *
 * Fetches the latest disposable email domains from:
 * https://github.com/disposable-email-domains/disposable-email-domains
 *
 * Usage: pnpm run update-disposable
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SOURCES = [
  // Primary source
  'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf',
];

async function fetchDomains(url: string): Promise<string[]> {
  console.log(`Fetching: ${url}`);
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status}`);
  }

  const text = await response.text();

  return text
    .split('\n')
    .map((line) => line.trim().toLowerCase())
    .filter((line) => line && !line.startsWith('#'));
}

async function main() {
  console.log('Updating disposable domains list...\n');

  const allDomains = new Set<string>();

  for (const source of SOURCES) {
    try {
      const domains = await fetchDomains(source);
      domains.forEach((d) => allDomains.add(d));
      console.log(`  Found ${domains.length} domains\n`);
    } catch (error) {
      console.error(`  Error fetching source: ${error}\n`);
    }
  }

  console.log(`Total unique domains: ${allDomains.size}`);

  // Sort domains for consistent output
  const sortedDomains = Array.from(allDomains).sort();

  // Generate TypeScript file
  const outputPath = join(
    __dirname,
    '../server/data/disposable-domains.ts'
  );

  const content = `/**
 * Known disposable email domains
 * Source: https://github.com/disposable-email-domains/disposable-email-domains
 *
 * Auto-generated by: pnpm run update-disposable
 * Last updated: ${new Date().toISOString()}
 * Total domains: ${sortedDomains.length}
 */

export const DISPOSABLE_DOMAINS: Set<string> = new Set([
${sortedDomains.map((d) => `  '${d}',`).join('\n')}
]);

/**
 * Check if a domain is a known disposable email provider
 */
export function isDisposableDomain(domain: string): boolean {
  return DISPOSABLE_DOMAINS.has(domain.toLowerCase());
}
`;

  writeFileSync(outputPath, content, 'utf-8');
  console.log(`\nWrote ${sortedDomains.length} domains to ${outputPath}`);
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
